### ISSUE TITLE
Distill related question

### ISSUE THREAD

**Issue by yogeshkodei** [apache/incubator-flagon-useralejs#42] opened 2021-03-04 03:05 UTC
Is there any updated version of Distill? Documentation says it is not maintained. WHat is the alternative?

**Comment by poorejc** [comment] 2021-03-04 03:34
Hi, not currently maintained. We're refactoring that entire project into a python package rather than a server side implementation. At the moment we just have a few examples of ETL ops in a python notebook. I will note that this is a near term project. Let me know if you'd like to contribute, and feel free to add any tickets to the distill repo: https://github.com/apache/incubator-flagon-distill/issues

You'll see more work on this soon.

If you're looking for ways of displaying, aggregating, or doing some forensics, we do have some pre-constructed kibana dashboards and viz components running in an ELK 6.8 stack in our top level project.

**Comment by yogeshkodei** [comment] 2021-03-04 05:45
Thanks for the update. 

What would be the right stack to use in conjunction with UserALE.js in order to analyze and visualize what is logged?

**Comment by poorejc** [comment] 2021-03-04 14:03
We like ELK. Elastic has excellent products with open source versions that allow for scale. Kibana is a nice dashboard built on top of ELK for visualization and we have a lot of examples of that. Here is a sample single-node stack: https://github.com/apache/incubator-flagon/tree/master/docker

The stack runs great on Docker desktop, however, I do have to modify instructions for 'docker-machine' commands as Docker Desktop has migrated to their own virtualization solution (that's on my list of things to do this week). 'docker-machine' is in maintenance.

If you want to scale out an ELK stack, you can jump into our configs in the above example and modify this project, which is an excellent cluster build of ELK: https://github.com/deviantony/docker-elk

**Comment by poorejc** [comment] 2021-03-05 03:12
So, I updated our instructions over at https://github.com/apache/incubator-flagon/tree/master/docker to account for recent changes in docker desktop. You'll note some tickets in issues over at the top level repo for building out a true elastic cluster (we do point to good examples such as above). However, once you see our index, you'll note its pretty easy to point userale to any ELK build you put together and start logging and visualizing. ...We're also interested in Apache Superset. Any co-development you want to put in, we're happy to put in effort on our side.

**Comment by yogeshkodei** [comment] 2021-03-05 04:08
Thanks. We were also considering Apache Superset. Wouldn’t UserALE work with just ELK?

**Comment by poorejc** [comment] 2021-03-05 17:16
Yes, but the two are not mutually exclusive. UserALE works with just ELK. However, Kibana's visualization capability is limited primarily to aggregation--it doesn't do rich analytics, it's a display. That may be fine for your use case (for many interested in traffic and usage analysis, it is). However, we're interested in Apache Superset because it has connectors for ElasticSearch and could offer more complex analytical capabilities (and probably visualization, too). Superset would be an enhancement on top of the ELK stack, not a replacement. We like ELK not just because of the convenience of Kibana, but also for it's indexing, scalability, and search-ability. Superset examples would give our users more options for how to use and visualize UserALE.js data. Turning Distill into a Python library, would also give users a way of building on and injecting those examples into a UserALE>ELK>Superset pipeline, we think. Still exploring the concept.

**Comment by yogeshkodei** [comment] 2021-03-05 18:35
Thanks. Is there any gallery of what some of the analytics looks like out of UserALE outputs?

**Comment by poorejc** [comment] 2021-03-06 02:54
We have some screens of kibana dashboards in our incubator-flagon/docker README: https://github.com/apache/incubator-flagon/tree/master/docker

I just added some more screens here: https://github.com/apache/incubator-flagon/tree/master/site/images

Unfortunately, the project (Flagon) was started in a company that wanted to keep all the advanced analytics proprietary. That's changed now, so you can expect some of that know-how getting pushed to the open source.

For some examples of some of the things we've done with Flagon in past that are public, you can check out some of our pubs:
https://www.researchgate.net/project/Apache-Flagon-Incubating

Can you tell us a little more about your use-case. What do you want to use UserALE for--business analytics, automation, user research?

**Comment by yogeshkodei** [comment] 2021-03-06 23:31
We would like to use it for User research/analytics. In addition analyze how a user is using the system and then use it for improving the application.

**Comment by poorejc** [comment] 2021-03-07 01:48
Thanks--helpful. You can mock some displays in Kibana that will give you something like funnels for "listening" to whether users are progressing through specific sequences. But, sounds like you want something a little deeper. That's on the slate with the Distill refactor, but it'll take a little time--we'll start with workflow definition and segmentation then move into some work with graphs. You are more than welcome to work with us on it!

**Comment by snehalghute** [comment] 2021-03-08 13:15
we got following error while running docker-compose up -d logstash
ERROR: for logstash  Cannot start service logstash: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/d/Work/incubator-flagon-master/docker/logstash/6.8.2/pipeline/logstash-userale.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/c5926c1ea9b8ce3f407194e77f0e831caf06114985f43db07bee21ddc638b9fc/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/c5926c1ea9b8ce3f407194e77f0e831caf06114985f43db07bee21ddc638b9fc/merged/usr/share/logstash/pipeline/logstash-userale.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Encountered errors while bringing up the project.

This is coming as under volumes file are mapped as shown below:
 volumes:
      - ./logstash/6.8.2/pipeline/logstash-userale.conf:/usr/share/logstash/pipeline/logstash-userale.conf
      - ./logstash/6.8.2/templates/userale.json:/usr/share/logstash/templates/userale.json
  This error wont come if we specify path till folder. But then file mapping is not working.

Kindly let me know fix for the same.

Thanks

**Comment by snehalghute** [comment] 2021-03-09 03:07
Thanks for reply. I am running docker from windows machine. I created hyper-v VM.

**Comment by poorejc** [comment] 2021-03-10 03:16
> Thanks for reply.
> <img alt="DockerInitilizeError" width="510" src="https://user-images.githubusercontent.com/2253726/110413860-a378be80-80b4-11eb-97d5-8bda539748a0.png">
> I am running docker from windows10 machine. I created hyper-v VM. I get error as shown in image while initializing docker.
> 
> Thanks

This is an issue with your docker engine. I can't help you with this.

**Comment by poorejc** [comment] 2021-03-10 03:31
> Logstash is shut down due to below error:
> �[33mlogstash_1 |�[0m [2021-03-09T11:44:29,818][INFO ][logstash.runner ] Starting Logstash {"logstash.version"=>"6.8.2"}
> �[33mlogstash_1 |�[0m [2021-03-09T11:44:29,856][INFO ][logstash.agent ] No persistent UUID file found. Generating new UUID {:uuid=>"d83369d7-e66a-4829-b4b6-d3e8536bcae7", :path=>"/usr/share/logstash/data/uuid"}
> �[33mlogstash_1 |�[0m [2021-03-09T11:44:30,492][INFO ][logstash.config.source.local.configpathloader] No config files found in path {:path=>"/usr/share/logstash/pipeline/*"}
> �[33mlogstash_1 |�[0m [2021-03-09T11:44:30,500][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
> �[33mlogstash_1 |�[0m [2021-03-09T11:44:30,856][INFO ][logstash.agent ] Successfully started Logstash API endpoint {:port=>9600}
> �[33mlogstash_1 |�[0m [2021-03-09T11:44:35,771][INFO ][logstash.runner ] Logstash shut down.
> 
> Config file present at /usr/share/logstash/pipeline with required access.
> 
> Thanks

Plz send me some info about your Docker Engine and Compose version. 

I tore down my docker and ELK builds on my Windows 10 box, started from scratch with a fresh install of Docker Desktop (latest) and can't replicate this error. Note that this is essentially the same issue you reported below. You can't get config files copied from your HDD to your VM.

If you can get Docker Desktop stable on your machine--Docker needs to initialize. I suggest you follow the directions to download docker-machine and try the instructions as I've written them (with docker-engine). 


If that doesn't work, try to build this ELK distro:

 https://github.com/deviantony/docker-elk/tree/release-6.x

It uses the same images we do, but it is a full cluster and very widely used. If you can't get this to run then I'm afraid the problem is on your side. Once you get this running, i can work with you to modify the templates and configs for UserALE data. You can also import our dashboards right in. That being said, ES should be able to dynamically index UserALE data sent to Logstash's TCP input (pt 5000 in this build I think). Meaning that you can see immediately if you're getting logs into ES with this build. That  you can build it will tell me something too.

Sorry I can't be more helpful. These are new error for us.

**Comment by snehalghute** [comment] 2021-03-10 14:49
Issue is solved now. Now I can see sample application data under Kibana.
can you please help me how I can configure userALE in my application for loading data under ELK?

**Comment by yogeshkodei** [comment] 2021-03-10 17:45
> > Logstash is shut down due to below error:
> > �[33mlogstash_1 |�[0m [2021-03-09T11:44:29,818][INFO ][logstash.runner ] Starting Logstash {"logstash.version"=>"6.8.2"}
> > �[33mlogstash_1 |�[0m [2021-03-09T11:44:29,856][INFO ][logstash.agent ] No persistent UUID file found. Generating new UUID {:uuid=>"d83369d7-e66a-4829-b4b6-d3e8536bcae7", :path=>"/usr/share/logstash/data/uuid"}
> > �[33mlogstash_1 |�[0m [2021-03-09T11:44:30,492][INFO ][logstash.config.source.local.configpathloader] No config files found in path {:path=>"/usr/share/logstash/pipeline/*"}
> > �[33mlogstash_1 |�[0m [2021-03-09T11:44:30,500][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
> > �[33mlogstash_1 |�[0m [2021-03-09T11:44:30,856][INFO ][logstash.agent ] Successfully started Logstash API endpoint {:port=>9600}
> > �[33mlogstash_1 |�[0m [2021-03-09T11:44:35,771][INFO ][logstash.runner ] Logstash shut down.
> > Config file present at /usr/share/logstash/pipeline with required access.
> > Thanks
> 
> Plz send me some info about your Docker Engine and Compose version.
> 
> I tore down my docker and ELK builds on my Windows 10 box, started from scratch with a fresh install of Docker Desktop (latest) and can't replicate this error. Note that this is essentially the same issue you reported below. You can't get config files copied from your HDD to your VM.
> 
> If you can get Docker Desktop stable on your machine--Docker needs to initialize. I suggest you follow the directions to download docker-machine and try the instructions as I've written them (with docker-engine).
> 
> If that doesn't work, try to build this ELK distro:
> 
> https://github.com/deviantony/docker-elk/tree/release-6.x
> 
> It uses the same images we do, but it is a full cluster and very widely used. If you can't get this to run then I'm afraid the problem is on your side. Once you get this running, i can work with you to modify the templates and configs for UserALE data. You can also import our dashboards right in. That being said, ES should be able to dynamically index UserALE data sent to Logstash's TCP input (pt 5000 in this build I think). Meaning that you can see immediately if you're getting logs into ES with this build. That you can build it will tell me something too.
> 
> Sorry I can't be more helpful. These are new error for us.

Greetings:
We would like to get the following basic information:
1. How many unique users have used the application in a day?
2. How many unique users have used the application in a week?
3. How many unique users have used the application in a month?
4. What is the sequence of clicks taken usually by users and how many users use the similar sequence?
5. Not sure if this is possible “What columns do people normally hide to accomplish their work”?
6. How much time does a user spend on the application on an average per day?

Would greatly appreciate any assistance in setting up the above reports.

I know you had mentioned that the company that started the project have changed their thought process in making advanced analytics available to the general audience. Any thoughts on when this would be available?

**Comment by poorejc** [comment] 2021-03-11 02:04
> Issue is solved now. Now I can see sample application data under Kibana.

That's awesome!

**Comment by poorejc** [comment] 2021-03-11 02:17
Comments inline!


> Greetings:
> We would like to get the following basic information:

Lots of this info isnt basic--people pay people or services for some of this stuff. I can give what we have, and we can help build what you need, but we need tickets and could use contributions or co-development.

> 
> 1. How many unique users have used the application in a day?

This is already baked into our dashboard. You can do unique users, hosts, whatever you want.

> 2. How many unique users have used the application in a week?

This is already baked into our dashboard. Just a time filter on the same stuff as above.

> 3. How many unique users have used the application in a month?

This is already baked into our dashboard. Just a time filter on the same stuff as above.

> 4. What is the sequence of clicks taken usually by users and how many users use the similar sequence?

This is really advanced stuff and requires some processing--same for flagon as for any other tool or service. This takes some segmentation, some modeling, and some inference. This is on my list of things to get going in distill and I have an idea for how to do this, but we could use some help on this. There's also the issue of deployment. Kibana can't do the processing, so you could work the analytical side as a python microservice pushing back to the same or different index in ES (then can be displayed in Kibana). I'd like to explore superset for this pipeline, though.

So, no this isn't currently available.

> 5. Not sure if this is possible “What columns do people normally hide to accomplish their work”?

If you know the DOM path to that feature, or what that behavior looks like, then this can be listened for.

> 6. How much time does a user spend on the application on an average per day?

Tricky in Kibana, b/c it doesn't really do time-date math, but there might be a way to do this--would need to experiment.

> 
> Would greatly appreciate any assistance in setting up the above reports.

I have a little bit of time off late next week (Thurs). I could give you an hour between 0900-1530 EST US. send me some times to poorejc@apache.org and I can set up a zoom call to give you some pointers.
> 
> I know you had mentioned that the company that started the project have changed their thought process in making advanced analytics available to the general audience. Any thoughts on when this would be available?

Never. Sorry. I sent you all the public reports that there are on that earlier work. You're welcome to reverse engineer. Should be OK as long as you don't yourself try and sell that (some of it is patented).

**Comment by yogeshkodei** [comment] 2021-03-11 03:45
> Comments inline!
> 
> > Greetings:
> > We would like to get the following basic information:
> 
> Lots of this info isnt basic--people pay people or services for some of this stuff. I can give what we have, and we can help build what you need, but we need tickets and could use contributions or co-development.
> 
> > 1. How many unique users have used the application in a day?
> 
> This is already baked into our dashboard. You can do unique users, hosts, whatever you want.
> 
> > 1. How many unique users have used the application in a week?
> 
> This is already baked into our dashboard. Just a time filter on the same stuff as above.
> 
> > 1. How many unique users have used the application in a month?
> 
> This is already baked into our dashboard. Just a time filter on the same stuff as above.
> 
> > 1. What is the sequence of clicks taken usually by users and how many users use the similar sequence?
> 
> This is really advanced stuff and requires some processing--same for flagon as for any other tool or service. This takes some segmentation, some modeling, and some inference. This is on my list of things to get going in distill and I have an idea for how to do this, but we could use some help on this. There's also the issue of deployment. Kibana can't do the processing, so you could work the analytical side as a python microservice pushing back to the same or different index in ES (then can be displayed in Kibana). I'd like to explore superset for this pipeline, though.
> 
> So, no this isn't currently available.
> 
> > 1. Not sure if this is possible “What columns do people normally hide to accomplish their work”?
> 
> If you know the DOM path to that feature, or what that behavior looks like, then this can be listened for.
> 
> > 1. How much time does a user spend on the application on an average per day?
> 
> Tricky in Kibana, b/c it doesn't really do time-date math, but there might be a way to do this--would need to experiment.
> 
> > Would greatly appreciate any assistance in setting up the above reports.
> 
> I have a little bit of time off late next week (Thurs). I could give you an hour between [0900-1530](tel:0900-1530) EST US. send me some times to [poorejc@apache.org](mailto:poorejc@apache.org) and I can set up a zoom call to give you some pointers.
> 
> > I know you had mentioned that the company that started the project have changed their thought process in making advanced analytics available to the general audience. Any thoughts on when this would be available?
> 
> Never. Sorry. I sent you all the public reports that there are on that earlier work. You're welcome to reverse engineer. Should be OK as long as you don't yourself try and sell that (some of it is patented).

Can Apache Flagon be bundled within our application? While we will not be charging our customers for it we would definitely charge for any services work thereof. Is that permissible?

**Comment by poorejc** [comment] 2021-03-11 19:02
Yes. Absolutely Flagon can be bundled in your tool. We're an Apache project and everything in these repos is free open-source, licensed under ALv2. I was referring to some of the analytical methods in that papers I sent you--most of that work isn't open source. We're trying to backfill our open source analytical capabilities through the Distill project. Sorry for the confusion. 

You can bundle useralejs as either script tag or npm module. All free and open source under ALv2. The same is true of the ES stack (altough we don't license that, only the open source images from ELK are used). The same will also be true of anything we push through the distill project. The idea behind refactoring that as a python project is to distribute that (under ALv2) through PyPI.

**Comment by yogeshkodei** [comment] 2021-03-11 19:34
> Yes. Absolutely Flagon can be bundled in your tool. We're an Apache project and everything in these repos is free open-source, licensed under ALv2. I was referring to some of the analytical methods in that papers I sent you--most of that work isn't open source. We're trying to backfill our open source analytical capabilities through the Distill project. Sorry for the confusion.
> 
> You can bundle useralejs as either script tag or npm module. All free and open source under ALv2. The same is true of the ES stack (altough we don't license that, only the open source images from ELK are used). The same will also be true of anything we push through the distill project. The idea behind refactoring that as a python project is to distribute that (under ALv2) through PyPI.

When you mentioned “ I was referring to some of the analytical methods in that papers I sent you--” - which papers are you referring to? Don’t think I got any. Can you please share the same?

**Comment by poorejc** [comment] 2021-03-12 02:13
Sorry, had posted a link to our researchgate site that has some of our published papers, which showcase a number of analytical approaches we have taken to modeling workflows with the same or similar kind of logging that useralejs offers. THe link is here: https://www.researchgate.net/project/Apache-Flagon-Incubating

Again, everything you see in our repos is 100% Apache v2 Licensed Code. It is free to use, and yes as long as you abide by the license terms for distribution (in apache v2) you can sell services against it. See our LICENSE file in the top level repo. Some of the analytics we have built in the past for past employers are not in the repos and remain proprietary to that organization. Sorry for the confusion.

**Comment by yogeshkodei** [comment] 2021-03-12 02:28
Thanks a ton!

**Comment by poorejc** [comment] 2021-03-12 02:30
Cool. Just sent you an email. Let's close this thread. After we connect, we can start peeling out any new tickets that arise in the right repos (incubator-flagon, incubator-flagon-useralejs, incubator-flagon-distill). Thanks!

**Closed by poorejc** 2021-03-12 02:30 UTC
